apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-be
  namespace: backend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: be-nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
