apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: be-nginx
  name: be-nginx
  namespace: backend-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: be-nginx
  type: NodePort
status:
  loadBalancer: {}
